version: '2.4'

services:
  snell-server:
    image: tslatop/snell-server:4.0.1
    restart: unless-stopped
    networks:
      - snell
    environment:
      - PSK=password # Change here
      - PORT=9102

  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: unless-stopped
    ports:
      - "9100:9100" # Change to your own port
    networks:
      - snell
    environment:
      - MODE=server
      - LISTEN=:::9100
      - SERVER=snell-server:9102
      - TLS=www.apple.com:443 # Change here
      - PASSWORD=password # Change here
      - V3=true

networks:
  snell:
    driver: bridge
